name: 🚀 PR
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on: [pull_request]
permissions:
  actions: write
  contents: read
  pull-requests: write
jobs:
  lint:
    name: ⬣ Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: biomejs/setup-biome@v2
      - run: biome ci . --reporter=github
  typecheck:
    name: 🔎 Type check
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: 'pnpm'
      - name: 📥 Download deps
        run: pnpm install --no-frozen-lockfile
      - name: 🔎 Type check
        run: pnpm run typecheck
